version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_EMAIL: /python-app/docker-credentials/email
    DOCKER_REGISTRY_USERNAME: /python-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /python-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /python-app/docker-credentials/url

phases:
  install:
    runtime-versions: 
      python: 3.11

  pre_build:
    commands:
      - pip install -r day-14/simple-python-app/requirements.txt

  build:
    commands:
      - cd day-14/simple-python-app
      - echo "Building Docker image"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/python-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/python-app:latest"

  post_build:
    commands:
      - echo "Build is Successful"
